apiVersion: apps/v1
kind: Deployment
metadata:
  name: case1
  labels:
    app: case1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: case1
  template:
    metadata:
      labels:
        app: case1
    spec:
      containers:
      - name: case1
        image: basu357/basurepo:1
        ports:
        - containerPort: 8080
